[[example]]
name = 'circles'

[[example]]
name = 'text'

[[example]]
name = 'tiled'

[[example]]
name = 'window'
required-features = ['piston_window_texture']

[dependencies]
bit-vec = '0.5.0'
image = '0.20.0'
piston2d-graphics = '0.26.0'
rayon = '1.0.2'
rusttype = '0.7.2'

[dependencies.piston_window]
optional = true
version = '0.82.0'

[features]
piston_window_texture = ['piston_window']

[package]
authors = ['Kai Schmidt <kaikaliischmidt@gmail.com>']
categories = [
    'multimedia',
    'multimedia::images',
    'rendering',
]
description = '''A buffer which can be used as a render target for Piston's graphics library. This buffer can be loaded from and/or saved to a file on disk. This allows for things like screenshots in games.'''
documentation = 'https://docs.rs/graphics_buffer/'
keywords = [
    'piston',
    'image',
    'rendering',
    'graphics',
]
license = 'MIT'
name = 'graphics_buffer'
readme = 'readme.md'
repository = 'https://github.com/kaikalii/graphics_buffer'
version = '0.4.1'
