[package]
name = "graphics_buffer"
version = "0.1.0"
authors = ["Kai Schmidt <kaikaliischmidt@gmail.com>"]
description = "A buffer which can be used as a render target for Piston's graphics library. This buffer can be loaded from and/or saved to a file on disk. This allows for things like screenshots in games."
repository = "https://github.com/kaikalii/graphics_buffer"
readme = "readme.md"
keywords = ["piston", "image", "rendering", "graphics"]
categories = ["multimedia", "multimedia::images", "rendering"]

[dependencies]
piston2d-graphics = "*"
image = "*"
bit-vec = "*"
rusttype = "*"
